# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PYSnoJQCHQwcRdkSetR3EQvG_w4K6nZu
"""

!python synthesize.py